arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/gen/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
preferred-supported-locales:
  - en
  - fr
