// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL4drFElwZo0FRjOPekUrpeZtmoHJnxgM',
    appId: '1:365508423653:web:35e8e91aeb544b4dec090c',
    messagingSenderId: '365508423653',
    projectId: 'vteam-cards',
    authDomain: 'cards.vteam.com',
    databaseURL:
        'https://vteam-cards-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vteam-cards.firebasestorage.app',
    measurementId: 'G-N327TRSY6H', //'G-VEDM41L0C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3q6If_CUMPKoo0zwCOgXnM30Poz8S30',
    appId: '1:365508423653:android:456e007b876e5501ec090c',
    messagingSenderId: '365508423653',
    projectId: 'vteam-cards',
    databaseURL:
        'https://vteam-cards-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vteam-cards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSbswmvoKnxPVo9i83GHyYZjJ4K0PoRU',
    appId: '1:365508423653:ios:1a2f65d35112c1efec090c',
    messagingSenderId: '365508423653',
    projectId: 'vteam-cards',
    databaseURL:
        'https://vteam-cards-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vteam-cards.firebasestorage.app',
    iosBundleId: 'com.vteam.cards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSbswmvoKnxPVo9i83GHyYZjJ4K0PoRU',
    appId: '1:365508423653:ios:1a2f65d35112c1efec090c',
    messagingSenderId: '365508423653',
    projectId: 'vteam-cards',
    databaseURL:
        'https://vteam-cards-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vteam-cards.firebasestorage.app',
    iosBundleId: 'com.vteam.cards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL4drFElwZo0FRjOPekUrpeZtmoHJnxgM',
    appId: '1:365508423653:web:35e8e91aeb544b4dec090c',
    messagingSenderId: '365508423653',
    projectId: 'vteam-cards',
    authDomain: 'cards.vteam.com',
    databaseURL:
        'https://vteam-cards-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vteam-cards.firebasestorage.app',
    measurementId: 'G-VEDM41L0C5',
  );
}
